version: '3.7'


services:
  # database
  mssql_db:
    container_name: ms-server-db
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: always
    environment:
      SA_PASSWORD: "Password123!"
      ACCEPT_EULA: "Y"
    ports:
      - 1433:1433
    expose:
      - 1433
  # front-end
  react_client:
    container_name: react_client
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - ./client:/app
      - /app/node_modules
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
  # backend
  dotNet_backend:
    container_name: webAPI
    links:
      - mssql_db
    build:
      context: ./webapi
      dockerfile: Dockerfile
    image: lure110/webapi:latest
    ports:
      - 5031:80
      - 7194:443
    environment:
      ASPNETCORE_URLS: "https://+;http://+"
      ASPNETCORE_HTTPS_PORT: 7194
      ASPNETCORE_ENVIRONMENT: Development
    volumes:
      - ${APPDATA}\microsoft\UserSecrets\:/root/.microsoft/usersecrets
      - ${USERPROFILE}\.aspnet\https:/root/.aspnet/https/
    depends_on:
      - mssql_db

    


